import "~/styles/globals.css";
import { ClerkProvider } from '@clerk/nextjs'

import { Inter } from "next/font/google";
import { dark } from "@clerk/themes";
import { ThemeProvider } from "~/components/providers/ThemeProvider";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (

    <ClerkProvider
    appearance={{
      baseTheme: dark
    }
    }
    >
    <html lang="en" suppressContentEditableWarning suppressHydrationWarning>
      <body className={`font-sans ${inter.variable}`}>
      <ThemeProvider
      attribute="class"
      defaultTheme="system"
      enableSystem
      disableTransitionOnChange
      >{children}
      </ThemeProvider>
      </body>

    </html>
    </ClerkProvider>

  );
}
